name: jaspr_riverpod
description: Riverpod for Jaspr
version: 0.3.6
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr:
    git:
      url: https://github.com/FlipSuite/jaspr_flutterflip.git
      path: packages/jaspr
  meta: ^1.9.1
  riverpod: ^2.3.2

dev_dependencies:
  jaspr_test: '>=0.1.0 <1.0.0'
  lints: ^2.1.0
  test: ^1.24.1
