name: jaspr_builder
description: Builders for jaspr
version: 0.9.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - jaspr
  - web
  - codegen
  - build-runner

dependencies:
  analyzer: ^5.4.0
  build: ^2.0.0
  collection: ^1.15.0
  dart_style: ^2.2.3
  glob: ^2.1.1
  jaspr:
    git:
      url: https://github.com/FlipSuite/jaspr_flutterflip.git
      path: packages/jaspr
  path: ^1.8.0
  source_gen: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^2.1.0
  test: ^1.22.0
